### ISSUE TITLE
Doc: Changelog page in documentation using snippets + towncrier

### ISSUE THREAD

**Issue by dunossauro** [dunossauro/videomaker-helper#33]
Install [`mkdocs-towncrier`](https://github.com/davfsa/mkdocs-towncrier) in docs group:

```bash
poetry add --group docs mkdocs-towncrier
```

Create changelog file `docs/CHANGELOG.md`:

```markdown
# Changelogs

:: towncrier-draft Unreleased


--8<-- "CHANGELOG.md"
```

Add config in Mkdocs.yaml:

```yaml
plugins:
  - towncrier

markdown_extensions:
  - pymdownx.snippets
```
